# Generated by Django 4.0.4 on 2022-05-25 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('std', models.CharField(choices=[('mscit', 'MSC IT'), ('bscit', 'BSC IT')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=10)),
                ('subjects', models.CharField(choices=[('math', 'Mathamatic'), ('sci', 'Science')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TeachersLoginInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('classes', models.CharField(choices=[('mscit', 'MSC IT'), ('bscit', 'BSC IT')], max_length=10)),
                ('subjects', models.CharField(choices=[('math', 'Mathamatic'), ('sci', 'Science')], max_length=10)),
                ('time_of_login', models.DateTimeField()),
                ('teacher_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendence.teachers')),
            ],
        ),
    ]
