# Generated by Django 4.0.4 on 2022-05-25 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0003_teachers_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='password',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='username',
        ),
    ]
