# Generated by Django 4.0.4 on 2022-05-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0004_remove_teachers_name_remove_teachers_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='subjects',
            field=models.CharField(choices=[('math', 'Mathamatic'), ('sci', 'Science')], max_length=80),
        ),
    ]
