# Generated by Django 4.0.4 on 2022-05-25 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendence', '0005_alter_teachers_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='std',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='teacherslogininfo',
            name='classes',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='teacherslogininfo',
            name='subjects',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='teacherslogininfo',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
