# Generated by Django 4.0.4 on 2022-05-25 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0006_alter_students_std_alter_teacherslogininfo_classes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherslogininfo',
            name='name',
        ),
        migrations.AddField(
            model_name='students',
            name='roll',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentsLoginInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_login', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.students')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.teacherslogininfo')),
            ],
        ),
    ]
